services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:stable
    ports:
      - '4566:4566'
    environment:
      - SERVICES=sqs,dynamodb,events
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  postgres_data: {}
