module.exports = {
  preset: 'ts-jest',
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '.',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '.+\\.(t|j)s$': 'ts-jest',
  },
  modulePaths: ['<rootDir>'],
  modulePathIgnorePatterns: [
    '<rootDir>/dist/',
    '<rootDir>/build/',
    '<rootDir>/coverage/',
    '<rootDir>/node_modules/',
    '<rootDir>/schematics/',
  ],
  collectCoverageFrom: [
    'src/**/*.{js,jsx,ts,tsx}',
    'domain/src/**/*.{js,jsx,ts,tsx}',
    '!e2e/**/*.{js,jsx,ts,tsx}',
    '!<rootDir>/node_modules/',
    '!schematics/**/*.{js,jsx,ts,tsx}',
    '!src/main.ts',
    '!src/instrumentation.ts',
    '!src/common/config/**/*.{js,jsx,ts,tsx}',
    '!src/common/exceptions/**/*.{js,jsx,ts,tsx}',
    '!src/common/interceptors/**/*.{js,jsx,ts,tsx}',
    '!src/common/strategies/**/*.{js,jsx,ts,tsx}',
    '!src/**/*.module.{js,jsx,ts,tsx}',
    '!src/common/migrations/**/*.{js,jsx,ts,tsx}',
    '!{src,domain}/**/*.interface.{js,jsx,ts,tsx}',
    '!{src,domain}/**/index.{js,jsx,ts,tsx}',
  ],
  coverageDirectory: './coverage',
  testEnvironment: 'node',
  verbose: true,
  reporters: [
    'default',
    ['jest-junit', {outputDirectory: 'coverage', outputName: 'report.xml'}],
  ],
  coverageReporters: ['lcov', 'cobertura'],
};
