apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: kira-take-home-test-backend-config
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /health
