name: Application CI/CD

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - run: npm install
      - run: npm run build
      - run: npm run test
      - run: npm run lint

  build_and_push_image:
    runs-on: ubuntu-latest
    needs: ci
    if: github.event_name == 'push'
    permissions:
      contents: 'read'
      id-token: 'write'
    outputs:
      image_tag: ${{ steps.build-and-push.outputs.image_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/94200964730/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-deployer@kiratakehometest.iam.gserviceaccount.com'
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Configure Docker
        run: gcloud auth configure-docker
      - name: Build and push Docker image
        id: build-and-push
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/kira-take-home-test:${IMAGE_TAG} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/kira-take-home-test:${IMAGE_TAG}
          echo "::set-output name=image_tag::${IMAGE_TAG}"

  deploy_dev:
    runs-on: ubuntu-latest
    needs: build_and_push_image
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/feature/')
    environment: development
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/94200964730/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-deployer@kiratakehometest.iam.gserviceaccount.com'
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: kira-take-home-test-cluster
          location: us-central1
      - name: Create/Update Kubernetes Secret
        run: |
          kubectl create secret generic app-secrets \
            --from-literal=DB_HOST=${{ secrets.DB_HOST }} \
            --from-literal=DB_PORT=${{ secrets.DB_PORT }} \
            --from-literal=DB_USERNAME=${{ secrets.DB_USERNAME }} \
            --from-literal=DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --from-literal=DB_NAME=${{ secrets.DB_NAME }} \
            --from-literal=SERVICE_NAME=${{ secrets.SERVICE_NAME }} \
            --from-literal=COLLECTION_NAME=${{ secrets.COLLECTION_NAME }} \
            --dry-run=client -o yaml | kubectl apply -f -
      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/
          kubectl set image deployment/kira-take-home-test kira-take-home-test=gcr.io/${{ secrets.GCP_PROJECT_ID }}/kira-take-home-test:${{ needs.build_and_push_image.outputs.image_tag }}

  deploy_prod:
    runs-on: ubuntu-latest
    needs: build_and_push_image
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: production
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/94200964730/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-deployer@kiratakehometest.iam.gserviceaccount.com'
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: kira-take-home-test-cluster
          location: us-central1
      - name: Create/Update Kubernetes Secret
        run: |
          kubectl create secret generic app-secrets \
            --from-literal=DB_HOST=${{ secrets.DB_HOST }} \
            --from-literal=DB_PORT=${{ secrets.DB_PORT }} \
            --from-literal=DB_USERNAME=${{ secrets.DB_USERNAME }} \
            --from-literal=DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --from-literal=DB_NAME=${{ secrets.DB_NAME }} \
            --from-literal=SERVICE_NAME=${{ secrets.SERVICE_NAME }} \
            --from-literal=COLLECTION_NAME=${{ secrets.COLLECTION_NAME }} \
            --dry-run=client -o yaml | kubectl apply -f -
      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/
          kubectl set image deployment/kira-take-home-test kira-take-home-test=gcr.io/${{ secrets.GCP_PROJECT_ID }}/kira-take-home-test:${{ needs.build_and_push_image.outputs.image_tag }}
